version: '3.7'

x-app: &app
  build:
    context: .
    dockerfile: ./Dockerfile.dev
    args:
      ELIXIR_VERSION: $ELIXIR_VERSION
      ERLANG_VERSION: $ERLANG_VERSION
      ALPINE_VERSION: $ALPINE_VERSION
  environment: &env
    MIX_ENV: dev
  image: lexin-on-whales:dev
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - build:/app/_build
    - mix:/root/.mix
    - hex:/root/.hex
    - node_modules:/app/assets/node_modules
  environment:
    <<: *env
    HISTFILE: /app/log/.bash_history
    DISPLAY: $X_WINDOWS_ADDRESS:0
    EDITOR: vi

# IMPORTANT:
#
# Do not forget to run `docker-compose run --rm phoenix ash` and compile application:
#
# mix deps.get && mix deps.compile
#
# BEFORE running `docker-compose up` (otherwise there is nothing compiled inside Docker container
# exists, and container cannot run `command` and simply exit)

services:
  phoenix:
    <<: *backend
    command: bash -c "test -f /app/_build/dev/lib/phoenix/ebin/Elixir.Mix.Phoenix.beam && mix phx.server"
    ports:
      - 4000:4000

volumes:
  build:
  mix:
  hex:
  node_modules:
