version: '3.7'

x-app: &app
  build:
    context: .
    dockerfile: .docker/Dockerfile.dev
    args:
      ELIXIR_VERSION: $ELIXIR_VERSION
      ERLANG_VERSION: $ERLANG_VERSION
      ALPINE_VERSION: $ALPINE_VERSION
  environment: &env
    MIX_ENV: dev
  image: lexin-on-whales:dev
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - build:/app/_build
    - mix:/root/.mix
    - hex:/root/.hex
    - node_modules:/app/assets/node_modules
    - ./log/.erlang-history:/root/.cache/erlang-history
  environment:
    <<: *env
    HISTFILE: /app/log/.shell_history
    DISPLAY: $X_WINDOWS_ADDRESS:0
    EDITOR: vi
    ERL_AFLAGS: -kernel shell_history enabled

services:
  phoenix:
    <<: *backend
    command: sh -c "mix phx.server"
    ports:
      - 4000:4000

volumes:
  build:
  mix:
  hex:
  node_modules:
