version: '3.7'

x-app: &app
  build:
    context: .
    dockerfile: ./.docker/Dockerfile
    args:
      ELIXIR_VERSION: ${ELIXIR_VERSION}
      NODE_MAJOR: ${NODE_MAJOR}
  environment: &env
    MIX_ENV: ${MIX_ENV}
  image: lexin-on-whales:0.0.1
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - build:/app/_build
    - mix:/root/.mix
    - hex:/root/.hex
    - node_modules:/app/assets/node_modules
  environment:
    <<: *env
    HISTFILE: /app/log/.bash_history
    DISPLAY: ${X_WINDOWS_ADDRESS}:0
    EDITOR: vi

services:
  phoenix:
    <<: *backend
    command: bash -c "test -f /app/_build/dev/lib/phoenix/ebin/Elixir.Mix.Phoenix.beam && mix phx.server"
    ports:
      - 4000:4000

volumes:
  build:
  mix:
  hex:
  node_modules:
