name: Elixir CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  MIX_ENV: test

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test on Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}
    strategy:
      matrix:
        elixir: [1.16.0]
        otp: [26.2.1]
    steps:
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache deps
        uses: actions/cache@v3
        env:
          cache-name: deps-cache
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-${{ env.cache-name }}-

      - name: Cache build
        uses: actions/cache@v3
        env:
          cache-name: compiled-build-cache
        with:
          path: _build
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-
            ${{ runner.os }}-mix-

      - name: Install deps
        run: mix deps.get

      - name: Compile with warnings as errors
        run: mix compile --warnings-as-errors

      - name: Check code formatting
        run: mix format --check-formatted

      - name: Check for unused dependencies
        run: mix deps.unlock --check-unused

      - name: Analyze code
        run: mix credo suggest --ignore todo

      - name: Run tests
        run: mix test
